init4tech/trevm

- src/evm.rs
- src/ext.rs
- src/lib.rs
- src/states.rs
Adds 2 unchecked APIs:
- an Ext trait for the EVM that allows shortcut state manipulation
- mutable and via-closure access to block contexts on Trevm
Motivation:
Context control flow takes `&mut Evm`, rather than `&mut Trevm` (as the latter would require double-mutable borrowing, or adding an ugly trevm `InContext` state). Extra low-level APIs make it easier to implement complex logic in block contexts, and more complex lifecycles relying on the context
> Lower-level APIs

- src/evm.rs
- src/lifecycle/contexts.rs
- src/states.rs
- Add `HasBlock` and `HasTx` to match `HasCfg`
- Add `with_` to temporarily overwrite envs with closure guards
> feat: closure guards for with_env

- Cargo.toml
- src/driver/alloy.rs
- src/driver/bundle.rs
- src/driver/mod.rs
- src/evm.rs
- src/lib.rs
- src/macros.rs
- src/states.rs
Adds a simple `BundleDriver` trait, which can drive bundles to completion.
Conceptually, it starts from an `EvmNeedsTx` state, and ends there. This means that this driver simply allows to run a group of transactions, while applying post-multi-tx logic after. It *does not* open or close blocks. This also allows us to run several bundles, one after another.
This `BundleDriver` trait is then composed with a `BlockProcessor` struct, which then takes charge of implementing a `BundleDriver` for a combination of a bundle type, and a response type. This allows us, for example, to quickly grab bundles that conform to [flashbots bundles](https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-mev/src/eth_calls.rs#L13-L96), simulate them, and return a properly calculated & formatted response. …
> feat(`driver`): `BundleDriver` for driving bundles to completion

- Cargo.toml
- src/evm.rs
bounding the inner DB prevents usage with (e.g.) reth's stateproviderbox and stateproviderdatabase shims
> fix: remove Commit bound on finish as it is provided by State

- src/evm.rs
- src/ext.rs
- src/system/eip2935.rs
- src/test_utils.rs
A few small fixes including removing dbg statements and improving imports
> fix: remove dbgs, improve imports

- Cargo.toml
- src/journal/coder.rs
- src/journal/index.rs
- src/journal/mod.rs
- src/lib.rs
Add a serializable journal for bundlestate
This adds the `BundleStateIndex` which generates a sorted index over a `BundleState`. The index can be serialized to a sorted, canonical format. The format is playable forwards and backwards. I.e. it can be used to apply blocks, or to rollback the same block
> feat: serializable journal for bundlestate

- Cargo.toml
- examples/basic_transact.rs
- examples/fork_ref_transact.rs
- src/driver/alloy.rs
- src/fill/alloy.rs
- src/fill/traits.rs
- src/lib.rs
- src/lifecycle/output.rs
- src/lifecycle/receipt.rs
- src/system/eip2935.rs
- src/system/eip4788.rs
- src/system/eip4895.rs
- src/system/eip6110.rs
- src/system/eip7002.rs
- src/system/eip7251.rs
Bump alloy to 0.3.6. This is a breaking change
> dep: bump alloy to 0.3.6

- Cargo.toml
- examples/basic_transact.rs
- examples/fork_ref_transact.rs
- src/driver/alloy.rs
- src/fill/alloy.rs
- src/fill/mod.rs
- src/fill/traits.rs
- src/fill/zenith.rs
- src/lib.rs
- src/lifecycle/output.rs
- src/lifecycle/receipt.rs
- src/system/eip2935.rs
- src/system/eip4788.rs
- src/system/eip4895.rs
- src/system/eip6110.rs
- src/system/eip7002.rs
- src/system/eip7251.rs
Add a `Cfg` implementation that disables all disable-able gas checks
> feat: disable gas checks

- Cargo.toml
- src/driver/alloy.rs
- src/lib.rs
- src/lifecycle/output.rs
- src/system/eip6110.rs
- src/system/eip7002.rs
- src/system/eip7251.rs
New Pectra specs removed the structured requests, according to alloy. 
Changed tests are pulled from reth @ main
> refactor: bump alloy to 0.5.2, remove requests struct usage

- src/connect.rs
- src/lib.rs
Adds a simple DB connector trait
> feat: db connect trait

- src/connect.rs
- src/lib.rs
Modifies `DbConnect` to add a lifetime to allow output to borrow
Adds `EvmFactory<'a>` with shortcut functions 
This is supplemental to `revm::EvmBuilder` as it allows builder inputs to be captured and shared between threads. the builder can/should be used during instantiation
> Lifetimed EvmFactory

- Cargo.toml
- src/db/builder.rs
- src/db/cache_state.rs
- src/db/mod.rs
- src/db/sync_state.rs
- src/evm.rs
- src/lib.rs
Adds a concurrently accessible version of the `State<Db>` from Revm. This manages a cache that can be updated by multiple threads via dashmap and an rwlock. The transitions can NOT be shared and require `&mut self`. The idea is that we should `Arc` it and then drop the users and use `Arc::get_mut` to manage transitions
> `ConcurrentState`

- .github/workflows/rust-ci.yml
- Cargo.toml
- src/connect.rs
- src/db/sync_state.rs
- src/driver/alloy.rs
- src/driver/mod.rs
- src/evm.rs
- src/fill/zenith.rs
- src/journal/coder.rs
- src/journal/index.rs
- src/lib.rs
- src/lifecycle/output.rs
- src/system/eip6110.rs
- src/test_utils.rs
Removes no-std support. Closes ENG-602.
> chore: remove no-std support

- Cargo.toml
- src/fill/zenith.rs
As we moved out these types to zenith-types, we need to move this type impl here.
Closes ENG-728
> chore: move Block impl for `ZenithCallBundle` to trevm

- src/lib.rs
> fix: small docs improvements

- Cargo.toml
- src/db/mod.rs
- src/est.rs
- src/evm.rs
the basic transfer estimation failed when eip2930 or eip7702 attributes were present, by underestimating the gas required.
This is an edge case, as users don't generally attach spurious info that costs money, but regularly encountered during testing things like `eth_estimateGas`
> fix: gas estimation for simple transfers

- Cargo.toml
- README.md
- src/fill/alloy.rs
Previous logic appears to be erroneous, and never sets prevrandao
always setting is safe, as it cannot be accessed outside of the post-merge specs
> Always set randao in alloy block filler

- Cargo.toml
- README.md
- src/est.rs
- src/evm.rs
- src/fill/alloy.rs
- src/fill/fillers.rs
- src/lib.rs
- src/macros.rs
Changes the allowance interface to make it usable when no TX is loaded, for any account.
This is a non-semver breaking change, and i have expanded on repo policy there in the readme.
includes drive-by cleanup of lints and compilation errors for no-default-features and all features
> Allowance interface tweaks

- Cargo.toml
- src/evm.rs
- src/fill/alloy.rs
- src/fill/zenith.rs
- src/journal/coder.rs
- src/system/eip6110.rs
Bumps deps to match reth @ 1.2.0, removes separate deps on alloy-rlp and alloy-sol-types
this is a breaking change, as per policy in readme
> chore: bump alloy and zenith deps

- src/driver/alloy.rs
- src/driver/block.rs
- src/driver/bundle.rs
- src/driver/chain.rs
- src/evm.rs
Drivers SHOULD be able to modify their DB state. Without this bound they can't effectively increment balances (e.g.)
> fix: restore commit bounds to drivers

- Cargo.toml
- src/evm.rs
#85 incorrectly swapped the behavior of these, making the infallible ones fallible and vice versa
> fix: Unswap block overrides methods

- CONTRIBUTING.md
Adds a basic `Contributing.md` to the repo
> chore: contributing.md

- src/driver/alloy.rs
- src/evm.rs
- src/lib.rs
- src/macros.rs
rename the `unwrap_or_trevm_error` macro to conform to more common standards
drive-by: includes the link fix from #90
> refactor: trevm_try

- Cargo.toml
- src/builder.rs
- src/connect.rs
- src/driver/alloy.rs
- src/driver/block.rs
- src/driver/bundle.rs
- src/driver/chain.rs
- src/evm.rs
- src/system/eip2935.rs
- src/system/eip4788.rs
- src/system/eip4895.rs
- src/system/eip7002.rs
- src/system/eip7251.rs
- src/test_utils.rs
Ensure that inspectors always run. If you do not want an inspector, stick with the noop inspector
> fix: add inspector bounds and always inspect

- src/inspectors/layer.rs
- src/inspectors/mod.rs
- src/inspectors/set.rs
- src/inspectors/spanning.rs
- src/inspectors/stack.rs
- src/inspectors/timeout.rs
- src/lib.rs
- src/system/mod.rs
- src/test_utils.rs
- a spanning inspector that generates spans for EVM callframes
- a timeout inspector, that halts EVM execution after a timer has elapsed
- an inspector stack, that invokes a series of `&dyn Inspector` in order
- an inspector layerer that is generic and allows access to inners without erasing type info
> feature: utility inspectors

- Cargo.toml
- src/db/sync/cache.rs
- src/db/sync/state.rs
- src/driver/alloy.rs
- src/driver/block.rs
- src/driver/bundle.rs
- src/driver/chain.rs
- src/est.rs
- src/evm.rs
- src/inspectors/layer.rs
- src/journal/index.rs
- src/lifecycle/output.rs
- src/states.rs
Put the DB back in the driver traits to handle new Inspector trait generics
> fix: db in driver traits again

- Cargo.toml
- src/db/cow/mod.rs
- src/db/mod.rs
- src/db/traits.rs
- src/evm.rs
Adds traits for DBs with inner `Cache` types and impls `try_flatten` on `CacheOnWrite`
> feat: cachingdb traits

- src/evm.rs
- src/helpers.rs
- src/inspectors/mod.rs
Add convenience methods to disable prevrandao
> feat: disable prevrandao

- Cargo.toml
- src/builder.rs
> feat: add precompiles to builder

- src/evm.rs
- src/fill/alloy.rs
Bugfix: previously when populating from a transaction request, the max priority fee per gas field was ignored, leaving the gas field in revm txenv blank
> fix: populate MPFPG from tx request in 1559 transactions

- Cargo.toml
- src/fill/alloy.rs
Adds filler support for 7702 transactions
> feat: support 7702 txns when filling

- Cargo.toml
- src/est.rs
- src/evm.rs
- src/macros.rs
fixes gas estimation bug that would cause it to vastly overestimate
> fix: estimation min set to gas_used - 1 rather than to estimate - 1

- Cargo.toml
- src/evm.rs
- src/journal/coder.rs
- src/journal/mod.rs
- src/journal/update.rs
- src/states.rs
- src/system/eip2935.rs
- src/system/eip4788.rs
Adds a bit more journal work by porting a type from signet-sdk
> feat: more journal
